name: Feature request
description: Suggest an improvement or new capability
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: Describe the current limitation.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred approach.
      placeholder: Explain the behavior you want.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative ideas?
      placeholder: Optional.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: CI/CD use case, screenshots, logs, links.
      placeholder: Optional.
    validations:
      required: false
